language: python
sudo: false
dist: xenial
python:
    - "3.5"
    - "3.6"
    - "3.7"

addons:
    apt:
        update: true

before_install:
    - pip install virtualenv -U

install:
    - sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
    - pip install tox-travis

script:
    - tox
