name: Run python tests and quality control

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        sudo apt-get install libxml2-dev libxmlsec1-dev libxmlsec1-openssl
        sudo dpkg -l | grep libxml
        sudo dpkg -l | grep openssl
        python -m pip install --upgrade pip
        pip install tox wheel
    - name: Run tests
      run: |
        tox
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
